// Custom Aura preset tinted with the SchoolTrack brand blue (#3B82F6).
// Generated by walking the default Aura primary scale and substituting the
// closest Tailwind blue stop. Surface tokens stay default Aura zinc.
import Aura from '@primeuix/themes/aura'
import { definePreset } from '@primeuix/themes'

export const SchoolTrackPreset = definePreset(Aura, {
  semantic: {
    primary: {
      50:  '#eff6ff',
      100: '#dbeafe',
      200: '#bfdbfe',
      300: '#93c5fd',
      400: '#60a5fa',
      500: '#3B82F6',
      600: '#2563eb',
      700: '#1d4ed8',
      800: '#1e40af',
      900: '#1e3a8a',
      950: '#172554',
    },
    colorScheme: {
      dark: {
        primary: {
          color: '{primary.400}',
          contrastColor: '#ffffff',
          hoverColor: '{primary.300}',
          activeColor: '{primary.200}',
        },
        highlight: {
          background: 'color-mix(in srgb, {primary.400} 16%, transparent)',
          focusBackground: 'color-mix(in srgb, {primary.400} 24%, transparent)',
          color: '{primary.300}',
          focusColor: '{primary.200}',
        },
      },
    },
  },
})
